server:
  port: 6003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/



spring:
  application:
    name: gateway
  mybatis:
    mapper-locations: com.cloud.microblog.gateway.dao.mapper
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/microblog?characterEncoding=utf-8           # 数据库连接地址
    username: root                                  # 数据库用户名
    password: 563739007                            # 数据库连接密码
    filters: config,stat
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
  redis:
    #host地址
    host: 127.0.0.1
    #端口
    port: 6379
    jedis:
      pool:
        #最大连接数 0表示无限制
        max-active: 8
        #最大空闲处
        max-idle: 100
        #最大等待时间
        max-wait: 1000
        #连接池中的最小空闲连接
        min-idle: 0

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

#zuul 路由配置
zuul:
  routes:
    #搜索系统
    search:
      path: /search/**
      url: http://localhost:8700
    oauth2:
      path: /oauth2-server/**
      url: http://localhost:6001
    resource:
      path: /resource/**
      url: http://localhost:7002
    web:
      path: /cloud-web/**
      url: http://localhost:7005

  # 用户模块
    user-api:
      path: /server-api/**
      serviceId: Auth-User
  # 用户服务提供者
    authprovider-api:
      path: /security-provider-api/**
      serviceId: security-provider
  # 任务调度中心
    scheduler-quartz-api:
      path: /scheduler-quartz-api/**
      serviceId: scheduler-quartz
  # 服务注册中心
  # 访问注册中心，使用的是url,否则会报错
  # com.netflix.client.ClientException: Load balancer does not have available server for client
    eureka-server-api:
      path: /eureka-server-api/**
      url: http://localhost:8001/
logging:
  level:
      org.springframework.security: debug
      com.cloud: debug
      org.apache.shiro.session.mgt: error

