server:
  port: 8701
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

spring:
  application:
    name: microblog-sms

logging:
  level:
    com.cloud: debug

microblog:
  common:
    # 使能打印访问Url，在Controller方法上添加注解@PrintUrlAnno
    printUrlEnable: true
    # 使能打印方法执行耗时，在方法上添加注解@PrintUseTimeAnno
    printUseTimeEnable: true

