server:
  port: 6003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
spring:
  application:
    name: gateway
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

#zuul 路由配置
zuul:
  routes:
    #搜索系统
    search:
      path: /search/**
      url: http://localhost:8700
    #认证系统
    auth:
      path: /auth/**
      url: http://localhost:8773
    #私信系统
    chat:
      path: /chat/**
      url: http://localhost:8000
    # 服务注册中心
    # 访问注册中心，使用的是url,否则会报错
    # com.netflix.client.ClientException: Load balancer does not have available server for client
    center:
      path: /center/**
      url: http://localhost:8001

    # 用户模块
    user:
      url: http://localhost:8002
      # serviceId: user
      path: /user/**


logging:
  level:
    org.springframework.security: debug
    com.cloud: debug
    org.apache.shiro.session.mgt: error
    com.cloud.microblog.gateway.service.shiro.config: error

# 需要验证Token的路径
auth:
  #私信chat应用
  chat:
    name: chat
    paths:
      - /chat/needFilter
      - /chat/**
      - /chat/user
  # 用户模块应用
  user:
    name: user
    paths:
      - /user/user/info/**
      - /user/user/info
