spring:
  datasource:
    name: mysqldatasource
    url: jdbc:mysql://localhost:3306/microblog?characterEncoding=utf-8
    username: root
    password: 563739007
    # type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver